### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Papadoubulus** [tim03we/GunGame-Nukkit#2]
10:44:47 [ERROR] Throwing
java.lang.RuntimeException: java.lang.NullPointerException
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:443) [nukkit.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:732) [nukkit.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:721) [nukkit.jar:?]
        at cn.nukkit.Server.<init>(Server.java:561) [nukkit.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:119) [nukkit.jar:?]
Caused by: java.lang.NullPointerException
        at tim03we.gungame.Main.loadSettings(Main.java:176) ~[?:?]
        at tim03we.gungame.Main.onEnable(Main.java:56) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[nukkit.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:439) ~[nukkit.jar:?]
        ... 4 more
Wenn Ich Orther items anmache

**Comment by tim03we** [comment]
Fix
